name: publish to bintray

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: publish
      env:
        BINTRAY_USERNAME: ${{secrets.BINTRAY_USERNAME}}
        BINTRAY_PASSWORD: ${{secrets.BINTRAY_PASSWORD}}
      run: sbt publish
